### ISSUE TITLE
Latest pycnite (2024.5.27) does not have sdist on PyPI

### ISSUE THREAD

**Issue by sunpoet** [google/pycnite#21]
We (FreeBSD ports) mainly use sdist to build python modules.
Previous version (2023.10.11) of pycnite provided sdist (pycnite-2023.10.11.tar.gz) on PyPI.
Please also publish sdist of pycnite 2024.5.27 to PyPI.
Thanks.

**Comment by h-joo** [comment]
Thanks for pointing this out! I think there was some error during the upload last time. I can see it from my local machine, but it seems that it was just not uploaded. I've just re-uploaded it. 
I will close the PR as it seems not needed.

**Comment by sunpoet** [comment]
Thanks for fixing it so quickly.
